name: Release App
on:
  push:
    tags:
      - 'regression-[0-9]+.[0-9]+.[0-9]+'
      - 'regression-[0-9]+.[0-9]+.[0-9]+-rc[0-9]+'
      - 'preview-[0-9]+.[0-9]+.[0-9]+'
      - 'preview-[0-9]+.[0-9]+.[0-9]+-rc[0-9]+'
      - 'release-[0-9]+.[0-9]+.[0-9]+'
      - 'release-[0-9]+.[0-9]+.[0-9]+-rc[0-9]+'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "GITHUB_CONTEXT: $GITHUB_CONTEXT"
      - name: Set vars
        run: |  
          echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          echo "RELEASE_HASH=$(git rev-parse --short "$GITHUB_SHA")" >> $GITHUB_ENV
      - name: Print release info
        run: |
          echo "release tag/version: $RELEASE_VERSION"
          echo "release commit id: $RELEASE_HASH"
          echo "github.ref (the branch or tag that trigger the event): $GITHUB_REF"
      - name: Checkout github-actions repo
        uses: actions/checkout@v2-beta
        with:
          repository: ahoze-r7/avidan-github-actions
          path: github-actions
          ref: refs/tags/v1
      - name: run create-release-for-divvy-from-tag action
        id: createReleaseForDivvyFromTagCompositeAction
        uses: ./github-actions/create-release-for-divvy-from-tag
        with:
          releaseVersion: $RELEASE_VERSION
          releaseHash: $RELEASE_HASH
          gitUserName: "'alcide jenkins'"
          gitUserEmail: "'alcidejenkins@rapid7.com'"
